create table if not exists waitingtime (
  id bigint generated by default as identity primary key,
  queue bigint,
  timestamp timestamp with time zone default timezone('cet'::text, now()) not null,
  airport text
);

grant usage on schema public to anon, authenticated, service_role;

grant select
  on public.waitingtime
  to anon;

grant select, insert, update, delete
  on public.waitingtime
  to authenticated;

grant select, insert, update, delete
  on public.waitingtime
  to service_role;

alter table public.waitingtime
  enable row level security;

create policy "anon can read waitingtime"
  on public.waitingtime
  for select to anon
  using (true);