create table if not exists waitingtime (
  id bigint generated by default as identity primary key,
  t2WaitingTime bigint,
  t2WaitingTimeInterval text,
  deliveryId timestamp with time zone default timezone('cet'::text, now()) not null
);
