name: Publish Autogluon image for production

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  AUTOGLUON_NAME: ${{ github.repository }}_autogluon

jobs:
  tests:
    name: Run unit & functional tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        working-directory: ./autogluon
        run: |
          python -m pip install --upgrade pip
          # Install pipenv so we can use the Pipfile
          pip install pipenv
          # Install dev + default packages into the system environment
          pipenv install --dev --system --deploy
          # Ensure pytest itself is present (typically already via dev deps)
          pip install pytest

      - name: Run pytest
        working-directory: ./autogluon
        run: pytest -q

  build-autogluon:
    name: Build & push Docker image
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.4.1

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (linux/amd64)
        uses: docker/build-push-action@v4
        with:
          context: ./autogluon/
          file: ./autogluon/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.REGISTRY }}/${{ env.AUTOGLUON_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.AUTOGLUON_NAME }}:${{ github.sha }}