name: Publish NextJS image for production

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  NEXTJS_NAME: ${{ github.repository }}_nextjs

jobs:
  build-nextjs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2.1.0

    # Use Docker Buildx builder
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2.4.1

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker image (linux/amd64)
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ./frontend-nextgen/nextjs
        push: true
        file: ./frontend-nextgen/nextjs/Dockerfile
        platforms: linux/amd64
        tags: |
          ${{ env.REGISTRY }}/${{ env.NEXTJS_NAME }}:latest
          ${{ env.REGISTRY }}/${{ env.NEXTJS_NAME }}:${{ github.sha }}
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.NEXTJS_NAME }}

    - name: Push image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ./frontend-nextgen/nextjs
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
